### ISSUE TITLE
Minecraft presets.

### ISSUE THREAD

**Issue by pendragons-code** [pendragons-code/GALAHAD#2]
[+] Galahad
          [.] mincraft lava flow (1.5)
          [+] Pickaxe
                    [.] wooden: 1.15 seconds, 59 durability
                    [.] stone: 0.75 seconds, 131 durability                 
                    [.] iron: 0.4 seconds, 250 durability              
                    [.] gold: 0.25 seconds, 32 durability              
                    [.] diamond: 0.3 seconds, 1561 durability             
                    [.] netherite: 0.25 seconds, 2031 durability

**Comment by woon-seng-hong-xinmin** [comment]
FINISH THIS ASAP first national exams have already started

**Comment by pendragons-code** [comment]
So intend to make a minecraft branch, which i'll get someone to test for me.

**Comment by woon-seng-hong-xinmin** [comment]
The think worse mostly fine but there is some inconsistency, that being that the mouse sometimes does not hold down long enough to break the block.

**Comment by pendragons-code** [comment]
I was told it works fine, but some inconsistencies might occur (turns out it was not related at all.)
